import type {
  CompanyStyle,
  InterviewMode,
  InterviewDifficulty,
  NewEvalCaseRow,
  NewPromptVersionRow,
} from "@/db/schema";
import type { RubricKey } from "@/db/schema";

type RubricDimensionSeed = {
  id: string;
  key: string;
  label: string;
  description: string;
  maxScore: number;
};

type QuestionSeed = {
  id: string;
  mode: InterviewMode;
  title: string;
  prompt: string;
  followUps: readonly string[];
  questionFamily: string;
  difficulty: InterviewDifficulty;
  companyTags: readonly CompanyStyle[];
  interviewerGoal: string;
  followUpPolicy: string;
  coachingOutline: readonly string[];
  rubricKeys: readonly RubricKey[];
  sourceTag: string;
  orderIndex: number;
};

function buildRubricDimension(
  id: string,
  key: string,
  label: string,
  description: string,
): RubricDimensionSeed {
  return {
    id,
    key,
    label,
    description,
    maxScore: 5,
  };
}

function buildQuestion(input: QuestionSeed) {
  return input;
}

export const SEED_RUBRIC_DIMENSIONS = [
  buildRubricDimension(
    "rubric_behavioral_structure",
    "structure",
    "Structure",
    "How clearly the candidate frames the situation, action, and result.",
  ),
  buildRubricDimension(
    "rubric_behavioral_ownership",
    "ownership",
    "Ownership",
    "How unmistakably the candidate claims and defends their decisions.",
  ),
  buildRubricDimension(
    "rubric_behavioral_impact",
    "impact",
    "Impact",
    "How concretely the answer proves user, business, or systems change.",
  ),
  buildRubricDimension(
    "rubric_behavioral_communication",
    "communication",
    "Communication",
    "How compact, direct, and interruption-resistant the answer feels.",
  ),
  buildRubricDimension(
    "rubric_behavioral_adaptability",
    "adaptability",
    "Adaptability",
    "How well the answer handles skeptical or changing follow-ups.",
  ),
  buildRubricDimension(
    "rubric_coding_problem_framing",
    "problem-framing",
    "Problem framing",
    "How well the candidate clarifies requirements, constraints, and edge cases.",
  ),
  buildRubricDimension(
    "rubric_coding_solution_design",
    "solution-design",
    "Solution design",
    "How coherent the algorithmic plan is before implementation details.",
  ),
  buildRubricDimension(
    "rubric_coding_correctness",
    "correctness",
    "Correctness",
    "How convincingly the answer proves the algorithm is right.",
  ),
  buildRubricDimension(
    "rubric_coding_testing",
    "testing",
    "Testing",
    "How thoroughly the candidate validates normal and edge cases.",
  ),
  buildRubricDimension(
    "rubric_coding_optimization",
    "optimization",
    "Optimization",
    "How well the trade-off behind the final complexity is explained.",
  ),
  buildRubricDimension(
    "rubric_resume_credibility",
    "credibility",
    "Credibility",
    "How defensible the candidate's claims sound under direct challenge.",
  ),
  buildRubricDimension(
    "rubric_resume_scope",
    "scope",
    "Scope",
    "How clearly the answer defines the boundary of the candidate's responsibility.",
  ),
  buildRubricDimension(
    "rubric_resume_decision_quality",
    "decision-quality",
    "Decision quality",
    "How well technical decisions are justified against real alternatives.",
  ),
  buildRubricDimension(
    "rubric_resume_technical_depth",
    "technical-depth",
    "Technical depth",
    "How much mechanism-level detail the candidate can defend.",
  ),
  buildRubricDimension(
    "rubric_system_requirements",
    "requirements",
    "Requirements",
    "How explicitly the candidate sets scale, latency, and correctness assumptions.",
  ),
  buildRubricDimension(
    "rubric_system_architecture",
    "architecture",
    "Architecture",
    "How coherent the high-level design is before deep dives.",
  ),
  buildRubricDimension(
    "rubric_system_api_data_model",
    "api-data-model",
    "API and data model",
    "How well the interfaces and storage model fit the stated requirements.",
  ),
  buildRubricDimension(
    "rubric_system_scalability",
    "scalability",
    "Scalability",
    "How concretely throughput, bottlenecks, and fan-out are handled.",
  ),
  buildRubricDimension(
    "rubric_system_reliability",
    "reliability",
    "Reliability",
    "How well failure modes and degraded behavior are addressed.",
  ),
  buildRubricDimension(
    "rubric_system_tradeoffs",
    "trade-offs",
    "Trade-offs",
    "How effectively the design's costs are acknowledged and defended.",
  ),
 ] as const satisfies readonly RubricDimensionSeed[];

export const SEED_QUESTION_BANK = [
  buildQuestion({
    id: "question_behavioral_ownership_01",
    mode: "behavioral",
    title: "Inherited reliability issue",
    prompt: "Tell me about a time you inherited something messy and had to make it reliable.",
    followUps: [
      "What did you personally own inside the turnaround?",
      "What changed after your decision shipped?",
      "What would break if the same issue happened at twice the scale?",
    ],
    questionFamily: "behavioral-ownership",
    difficulty: "standard",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Pressure ownership and measurable impact.",
    followUpPolicy: "Keep the candidate in first-person language and ask for proof when the answer drifts into team-wide phrasing.",
    coachingOutline: [
      "Lead with stakes, not chronology.",
      "Name the decision you owned.",
      "Close with a measurable reliability or delivery outcome.",
    ],
    rubricKeys: ["structure", "ownership", "impact", "communication"],
    sourceTag: "behavioral_story",
    orderIndex: 1,
  }),
  buildQuestion({
    id: "question_behavioral_ownership_02",
    mode: "behavioral",
    title: "Unclaimed production problem",
    prompt: "Tell me about a production problem that was not originally yours but that you ended up driving to resolution.",
    followUps: [
      "Why did you step in when it was not assigned to you?",
      "How did you keep the scope contained?",
      "What metric or operational signal proved the fix mattered?",
    ],
    questionFamily: "behavioral-ownership",
    difficulty: "challenging",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Test whether the candidate can sound accountable without overstating authority.",
    followUpPolicy: "Probe on role clarity, trade-offs, and evidence instead of accepting generic leadership language.",
    coachingOutline: [
      "Differentiate initiative from title-based ownership.",
      "Explain the narrow decision you controlled.",
      "Prove the result with a reliability or customer signal.",
    ],
    rubricKeys: ["structure", "ownership", "impact", "adaptability"],
    sourceTag: "behavioral_story",
    orderIndex: 2,
  }),
  buildQuestion({
    id: "question_behavioral_conflict_01",
    mode: "behavioral",
    title: "Technical disagreement",
    prompt: "Tell me about a time you strongly disagreed with another engineer on a technical decision.",
    followUps: [
      "What did you do beyond just stating your opinion?",
      "How did the disagreement affect delivery or quality?",
      "What would you do differently if the disagreement involved your manager?",
    ],
    questionFamily: "behavioral-conflict",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Look for conflict handling without loss of technical rigor.",
    followUpPolicy: "Probe on how the candidate influenced the outcome instead of whether they were 'right.'",
    coachingOutline: [
      "Explain the disagreement in one sentence.",
      "Move quickly to your concrete action.",
      "End with what changed and what you learned.",
    ],
    rubricKeys: ["structure", "communication", "adaptability"],
    sourceTag: "behavioral_story",
    orderIndex: 3,
  }),
  buildQuestion({
    id: "question_behavioral_conflict_02",
    mode: "behavioral",
    title: "Cross-functional friction",
    prompt: "Describe a time product or leadership pushed for a solution you thought would hurt engineering quality.",
    followUps: [
      "How did you push back without becoming obstructionist?",
      "What trade-off did you accept anyway?",
      "How would you frame the same pushback to an executive audience?",
    ],
    questionFamily: "behavioral-conflict",
    difficulty: "stretch",
    companyTags: ["general", "amazon", "meta"],
    interviewerGoal: "Measure technical judgment under organizational pressure.",
    followUpPolicy: "Force the answer to articulate trade-offs and influence, not just principles.",
    coachingOutline: [
      "Name the risk crisply.",
      "Explain the trade-off you accepted.",
      "Show how you influenced the decision path.",
    ],
    rubricKeys: ["ownership", "impact", "communication", "adaptability"],
    sourceTag: "behavioral_story",
    orderIndex: 4,
  }),
  buildQuestion({
    id: "question_behavioral_failure_01",
    mode: "behavioral",
    title: "Launch that slipped",
    prompt: "Tell me about a launch or migration that did not go to plan.",
    followUps: [
      "What did you miss before launch day?",
      "What recovery decision did you personally make?",
      "How did the team change its process afterward?",
    ],
    questionFamily: "behavioral-failure",
    difficulty: "standard",
    companyTags: ["general", "meta"],
    interviewerGoal: "Check accountability and recovery quality after failure.",
    followUpPolicy: "Do not let the candidate hide in passive voice or collective ownership.",
    coachingOutline: [
      "Own the miss directly.",
      "Name the recovery decision you drove.",
      "Describe the durable process change afterward.",
    ],
    rubricKeys: ["ownership", "impact", "communication"],
    sourceTag: "behavioral_story",
    orderIndex: 5,
  }),
  buildQuestion({
    id: "question_behavioral_failure_02",
    mode: "behavioral",
    title: "Bad technical call",
    prompt: "Tell me about a technical decision you made that turned out to be wrong.",
    followUps: [
      "When did you realize it was wrong?",
      "How did you communicate the correction?",
      "What evidence would make you choose differently next time?",
    ],
    questionFamily: "behavioral-failure",
    difficulty: "challenging",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Test self-awareness and evidence-based correction.",
    followUpPolicy: "Push for the actual signal that proved the decision was wrong.",
    coachingOutline: [
      "State the bad assumption clearly.",
      "Show how you corrected course.",
      "Close with the decision rule you use now.",
    ],
    rubricKeys: ["structure", "ownership", "adaptability"],
    sourceTag: "behavioral_story",
    orderIndex: 6,
  }),
  buildQuestion({
    id: "question_behavioral_influence_01",
    mode: "behavioral",
    title: "No authority influence",
    prompt: "Tell me about a time you had to influence a technical direction without formal authority.",
    followUps: [
      "What made people listen?",
      "What resistance did you run into?",
      "What evidence moved the discussion forward?",
    ],
    questionFamily: "behavioral-influence",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Look for persuasion quality rather than title-based leverage.",
    followUpPolicy: "Keep the answer grounded in actions, artifacts, and evidence.",
    coachingOutline: [
      "Frame the problem before the persuasion tactic.",
      "Name the artifact or evidence you used.",
      "Show the concrete shift in decision or execution.",
    ],
    rubricKeys: ["ownership", "communication", "impact"],
    sourceTag: "behavioral_story",
    orderIndex: 7,
  }),
  buildQuestion({
    id: "question_behavioral_influence_02",
    mode: "behavioral",
    title: "Drive a standard",
    prompt: "Describe a time you raised the engineering bar by introducing a new standard or process.",
    followUps: [
      "Why was the old way not good enough?",
      "How did you get adoption instead of resentment?",
      "What signal told you the new standard was worth the effort?",
    ],
    questionFamily: "behavioral-influence",
    difficulty: "standard",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Measure how the candidate scales influence through systems.",
    followUpPolicy: "Probe on adoption mechanics and measurable impact.",
    coachingOutline: [
      "State the initial pain clearly.",
      "Explain the mechanism for adoption.",
      "End with the operational proof the new standard worked.",
    ],
    rubricKeys: ["structure", "impact", "communication"],
    sourceTag: "behavioral_story",
    orderIndex: 8,
  }),
  buildQuestion({
    id: "question_behavioral_ambiguity_01",
    mode: "behavioral",
    title: "Ambiguous problem",
    prompt: "Tell me about a time you had to make progress on an ambiguous technical problem with incomplete requirements.",
    followUps: [
      "What assumptions did you make first?",
      "How did you keep from building the wrong thing?",
      "What did you learn that changed your approach?",
    ],
    questionFamily: "behavioral-ambiguity",
    difficulty: "challenging",
    companyTags: ["general", "meta", "stripe"],
    interviewerGoal: "Test ambiguity handling and operating judgment.",
    followUpPolicy: "Ask for the specific assumptions and how they were validated.",
    coachingOutline: [
      "Open with the missing information.",
      "Describe the first assumption set.",
      "Show how you revised the plan with new evidence.",
    ],
    rubricKeys: ["structure", "adaptability", "impact"],
    sourceTag: "behavioral_story",
    orderIndex: 9,
  }),
  buildQuestion({
    id: "question_behavioral_ambiguity_02",
    mode: "behavioral",
    title: "Unclear priority trade-off",
    prompt: "Describe a time you had to choose between speed and technical quality with incomplete information.",
    followUps: [
      "What data did you wish you had?",
      "How did you communicate the trade-off?",
      "What happened after the decision landed?",
    ],
    questionFamily: "behavioral-ambiguity",
    difficulty: "stretch",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Surface decision quality under uncertainty and pressure.",
    followUpPolicy: "Force the candidate to pick and defend a trade-off rather than saying 'it depends.'",
    coachingOutline: [
      "Frame the trade-off explicitly.",
      "Explain the decision rule you used.",
      "Close with the consequence and what you monitored.",
    ],
    rubricKeys: ["ownership", "impact", "adaptability"],
    sourceTag: "behavioral_story",
    orderIndex: 10,
  }),
  buildQuestion({
    id: "question_behavioral_prioritization_01",
    mode: "behavioral",
    title: "Competing incidents",
    prompt: "Tell me about a time several urgent engineering problems hit at once and you had to prioritize.",
    followUps: [
      "What did you handle first and why?",
      "What did you deliberately deprioritize?",
      "How did you communicate the trade-offs to stakeholders?",
    ],
    questionFamily: "behavioral-prioritization",
    difficulty: "standard",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Evaluate prioritization under pressure.",
    followUpPolicy: "Ask why one path mattered more and what risk was accepted elsewhere.",
    coachingOutline: [
      "Lead with the prioritization rule.",
      "Explain the cost of what you delayed.",
      "Show what signal proved the choice was right.",
    ],
    rubricKeys: ["structure", "ownership", "communication"],
    sourceTag: "behavioral_story",
    orderIndex: 11,
  }),
  buildQuestion({
    id: "question_behavioral_prioritization_02",
    mode: "behavioral",
    title: "Limited resources",
    prompt: "Describe a time you had to cut scope or sequencing to deliver the most important engineering outcome.",
    followUps: [
      "What did you cut first?",
      "How did you decide the remaining slice was enough?",
      "How did you explain the cut to the rest of the team?",
    ],
    questionFamily: "behavioral-prioritization",
    difficulty: "challenging",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Check ruthless prioritization with credible trade-off framing.",
    followUpPolicy: "Probe on scope boundaries and stakeholder communication.",
    coachingOutline: [
      "State the original scope and what changed.",
      "Describe the cut you personally defended.",
      "Close with the benefit of the narrower plan.",
    ],
    rubricKeys: ["ownership", "impact", "communication"],
    sourceTag: "behavioral_story",
    orderIndex: 12,
  }),
  buildQuestion({
    id: "question_coding_arrays_01",
    mode: "coding",
    title: "Sliding window string",
    prompt: "Given a string, find the length of the longest substring without repeating characters. Talk through the solution before any code.",
    followUps: [
      "What edge cases do you clarify before solving?",
      "How do you know the window update logic stays correct?",
      "What is the complexity and what trade-off are you making?",
    ],
    questionFamily: "coding-sliding-window",
    difficulty: "standard",
    companyTags: ["general", "meta"],
    interviewerGoal: "Test structured reasoning on a classic sliding-window problem.",
    followUpPolicy: "Probe for invariants, edge cases, and why the chosen data structure works.",
    coachingOutline: [
      "Clarify constraints before touching the approach.",
      "State the invariant behind the window movement.",
      "Test duplicates, empties, and single-character strings.",
    ],
    rubricKeys: ["problem-framing", "solution-design", "correctness", "optimization"],
    sourceTag: "coding_reasoning",
    orderIndex: 13,
  }),
  buildQuestion({
    id: "question_coding_arrays_02",
    mode: "coding",
    title: "Longest stable window",
    prompt: "You are given an array of numbers and can change at most one value. What is the longest contiguous window that can be made strictly increasing?",
    followUps: [
      "What assumptions do you need to clarify first?",
      "How would you prove the algorithm handles boundary windows correctly?",
      "What simpler but slower solution would you reject?",
    ],
    questionFamily: "coding-sliding-window",
    difficulty: "stretch",
    companyTags: ["general", "google"],
    interviewerGoal: "Stress reasoning quality when the pattern is less obvious.",
    followUpPolicy: "Push for problem framing and proof, not just a guessed pattern.",
    coachingOutline: [
      "Clarify exact allowed operations.",
      "Explain the chosen state and why it is sufficient.",
      "Test boundaries and one-change edge cases.",
    ],
    rubricKeys: ["problem-framing", "correctness", "optimization"],
    sourceTag: "coding_reasoning",
    orderIndex: 14,
  }),
  buildQuestion({
    id: "question_coding_hashmap_01",
    mode: "coding",
    title: "Group shifted strings",
    prompt: "How would you group strings that belong to the same shifting sequence? Explain the representation before any code.",
    followUps: [
      "How do you normalize strings of different lengths?",
      "What would your pseudocode look like?",
      "How would you test collisions in your chosen key?",
    ],
    questionFamily: "coding-hashmap",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Evaluate representation choices and proof of correctness.",
    followUpPolicy: "Make the candidate justify the hash key and test strategy.",
    coachingOutline: [
      "Choose a stable representation first.",
      "Explain why two equivalent strings map to the same key.",
      "Test empty strings, singles, and wrap-around characters.",
    ],
    rubricKeys: ["solution-design", "correctness", "testing"],
    sourceTag: "coding_reasoning",
    orderIndex: 15,
  }),
  buildQuestion({
    id: "question_coding_hashmap_02",
    mode: "coding",
    title: "Near-duplicate detector",
    prompt: "Design a function that determines whether an array contains two values within k positions and t numeric distance.",
    followUps: [
      "What naive solution do you start from and why is it insufficient?",
      "Which data structure gets you to the better bound?",
      "Where are the tricky overflow or boundary cases?",
    ],
    questionFamily: "coding-hashmap",
    difficulty: "stretch",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Test the jump from brute force to a more careful data structure choice.",
    followUpPolicy: "Push on correctness and boundary handling, not just asymptotic complexity.",
    coachingOutline: [
      "State the baseline solution first.",
      "Explain the bucket or ordered-set trade-off clearly.",
      "Name the boundary cases before claiming correctness.",
    ],
    rubricKeys: ["problem-framing", "solution-design", "correctness", "optimization"],
    sourceTag: "coding_reasoning",
    orderIndex: 16,
  }),
  buildQuestion({
    id: "question_coding_graph_01",
    mode: "coding",
    title: "Word ladder reasoning",
    prompt: "Explain how you would find the shortest transformation sequence between two words, changing one letter at a time.",
    followUps: [
      "Why is breadth-first search the right tool here?",
      "How do you keep neighbor generation from dominating runtime?",
      "What cases would you test before saying you are done?",
    ],
    questionFamily: "coding-graph",
    difficulty: "challenging",
    companyTags: ["general", "meta"],
    interviewerGoal: "Measure graph reasoning and optimization storytelling.",
    followUpPolicy: "Make the candidate justify both traversal choice and runtime improvements.",
    coachingOutline: [
      "Define nodes and edges explicitly.",
      "Justify BFS before optimizing.",
      "Test no-path and same-word cases.",
    ],
    rubricKeys: ["solution-design", "correctness", "optimization", "testing"],
    sourceTag: "coding_reasoning",
    orderIndex: 17,
  }),
  buildQuestion({
    id: "question_coding_graph_02",
    mode: "coding",
    title: "Course schedule planning",
    prompt: "Talk through how you would detect whether a set of course prerequisites contains a cycle.",
    followUps: [
      "Would you use DFS, BFS, or both?",
      "How do you explain correctness without writing code?",
      "What follow-up would force you to change the design?",
    ],
    questionFamily: "coding-graph",
    difficulty: "standard",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Assess graph fundamentals and explanation quality.",
    followUpPolicy: "Ask for explicit invariants and failure cases instead of generic graph talk.",
    coachingOutline: [
      "Choose a traversal and justify it.",
      "Name the state that proves a cycle exists.",
      "Test disconnected graphs and empty prerequisite lists.",
    ],
    rubricKeys: ["problem-framing", "correctness", "communication"],
    sourceTag: "coding_reasoning",
    orderIndex: 18,
  }),
  buildQuestion({
    id: "question_coding_dp_01",
    mode: "coding",
    title: "Decode ways",
    prompt: "Explain how you would count the number of ways to decode a numeric string where 1-26 map to letters.",
    followUps: [
      "What subproblem definition makes the recurrence obvious?",
      "Where do leading zeroes break the reasoning?",
      "How would you reduce the space usage?",
    ],
    questionFamily: "coding-dp",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Test whether the candidate can narrate dynamic programming instead of jumping straight to formulas.",
    followUpPolicy: "Probe on state definition, invalid transitions, and space optimization.",
    coachingOutline: [
      "Define the DP state in plain language first.",
      "Explain zero-handling before recurrence details.",
      "Close with the space optimization trade-off.",
    ],
    rubricKeys: ["solution-design", "correctness", "optimization"],
    sourceTag: "coding_reasoning",
    orderIndex: 19,
  }),
  buildQuestion({
    id: "question_coding_dp_02",
    mode: "coding",
    title: "Constrained path score",
    prompt: "You can move through an array by taking one or two steps. Each position has a score and some are blocked. How do you maximize the total score?",
    followUps: [
      "What recurrence captures the constraint cleanly?",
      "How do blocked positions change the base cases?",
      "How would you test your recurrence against small examples?",
    ],
    questionFamily: "coding-dp",
    difficulty: "stretch",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Stress whether the candidate can build a recurrence from a custom prompt.",
    followUpPolicy: "Require plain-language reasoning before any formula-like shorthand.",
    coachingOutline: [
      "State the recurrence in words first.",
      "Explain how invalid states propagate.",
      "Use tiny hand-worked examples to prove correctness.",
    ],
    rubricKeys: ["problem-framing", "correctness", "testing"],
    sourceTag: "coding_reasoning",
    orderIndex: 20,
  }),
  buildQuestion({
    id: "question_coding_intervals_01",
    mode: "coding",
    title: "Meeting rooms",
    prompt: "How would you determine the minimum number of rooms needed for a set of meeting intervals?",
    followUps: [
      "What two plausible approaches would you consider first?",
      "Why does sorting help here?",
      "How would you explain correctness on overlapping boundaries?",
    ],
    questionFamily: "coding-intervals",
    difficulty: "standard",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Check structured interval reasoning and trade-off awareness.",
    followUpPolicy: "Push on approach comparison and correctness of boundary handling.",
    coachingOutline: [
      "Compare the heap and sweep-line options briefly.",
      "Explain the sorted order and what it enables.",
      "Test adjacent intervals and complete overlap.",
    ],
    rubricKeys: ["solution-design", "correctness", "communication"],
    sourceTag: "coding_reasoning",
    orderIndex: 21,
  }),
  buildQuestion({
    id: "question_coding_intervals_02",
    mode: "coding",
    title: "Merge and annotate intervals",
    prompt: "Describe how you would merge overlapping intervals while preserving the list of source ranges that contributed to each merged block.",
    followUps: [
      "What extra state do you need compared with the usual merge problem?",
      "How does that change your pseudocode?",
      "What edge case would most likely break a rushed implementation?",
    ],
    questionFamily: "coding-intervals",
    difficulty: "challenging",
    companyTags: ["general", "meta"],
    interviewerGoal: "Test whether the candidate adapts a familiar pattern to a richer output contract.",
    followUpPolicy: "Do not let the answer stop at the usual merge-intervals story; force the extra state explanation.",
    coachingOutline: [
      "State the output contract before the algorithm.",
      "Explain the extra carried state.",
      "Test equal boundaries and nested intervals.",
    ],
    rubricKeys: ["problem-framing", "solution-design", "testing"],
    sourceTag: "coding_reasoning",
    orderIndex: 22,
  }),
  buildQuestion({
    id: "question_coding_tree_01",
    mode: "coding",
    title: "Binary tree serialization",
    prompt: "Explain how you would serialize and deserialize a binary tree for network transport.",
    followUps: [
      "Which traversal order do you choose and why?",
      "How do you represent nulls without ambiguity?",
      "What tests prove round-trip correctness?",
    ],
    questionFamily: "coding-tree",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Evaluate tree reasoning plus API-contract discipline.",
    followUpPolicy: "Push on representation choices and proof of reversibility.",
    coachingOutline: [
      "Pick one traversal and defend it.",
      "Be explicit about null markers.",
      "Test round-trip equivalence with skewed trees.",
    ],
    rubricKeys: ["solution-design", "correctness", "testing"],
    sourceTag: "coding_reasoning",
    orderIndex: 23,
  }),
  buildQuestion({
    id: "question_coding_tree_02",
    mode: "coding",
    title: "Lowest common ancestor reasoning",
    prompt: "Talk through how you would find the lowest common ancestor of two nodes in a binary tree.",
    followUps: [
      "What changes if parent pointers exist?",
      "How do you explain correctness recursively?",
      "When would you prefer an iterative approach?",
    ],
    questionFamily: "coding-tree",
    difficulty: "standard",
    companyTags: ["general", "meta"],
    interviewerGoal: "Measure recursion reasoning and follow-up adaptability.",
    followUpPolicy: "Probe on proof, not just the memorized pattern.",
    coachingOutline: [
      "State the recursive meaning of the return value.",
      "Explain the base cases carefully.",
      "Name the iterative trade-off if the interviewer pushes there.",
    ],
    rubricKeys: ["solution-design", "correctness", "communication"],
    sourceTag: "coding_reasoning",
    orderIndex: 24,
  }),
  buildQuestion({
    id: "question_system_notifications_01",
    mode: "system-design",
    title: "Notification service",
    prompt: "Design a real-time notification service for a product with millions of active users.",
    followUps: [
      "Where does fan-out happen and what breaks first?",
      "How do you store user preferences and delivery state?",
      "What degraded behavior do you want during a traffic spike?",
    ],
    questionFamily: "system-notifications",
    difficulty: "challenging",
    companyTags: ["general", "meta"],
    interviewerGoal: "Test scale framing, fan-out design, and reliability trade-offs.",
    followUpPolicy: "Pressure assumptions, bottlenecks, and degraded behavior before implementation minutiae.",
    coachingOutline: [
      "State scale and latency assumptions immediately.",
      "Draw the write path and fan-out path separately.",
      "Name one bottleneck and one fallback mode before closing.",
    ],
    rubricKeys: ["requirements", "architecture", "scalability", "reliability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 25,
  }),
  buildQuestion({
    id: "question_system_notifications_02",
    mode: "system-design",
    title: "Cross-channel alerts",
    prompt: "Design a cross-channel alerting platform that can send push, email, and SMS with user-level preferences.",
    followUps: [
      "How does the API model user intent and delivery priority?",
      "Where do retries and idempotency live?",
      "How do you keep a channel outage from breaking the whole platform?",
    ],
    questionFamily: "system-notifications",
    difficulty: "stretch",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Measure multi-channel abstraction quality and failure isolation.",
    followUpPolicy: "Probe on queueing, idempotency, and per-channel degradation.",
    coachingOutline: [
      "Start with the contract and delivery guarantees.",
      "Separate orchestration from transport adapters.",
      "Close with outage handling and replay semantics.",
    ],
    rubricKeys: ["requirements", "api-data-model", "reliability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 26,
  }),
  buildQuestion({
    id: "question_system_feed_01",
    mode: "system-design",
    title: "Home feed",
    prompt: "Design a home feed service for a social product with ranking, fan-out, and freshness constraints.",
    followUps: [
      "Would you fan out on write or read and why?",
      "How do ranking and freshness pressure the architecture?",
      "What is the first scaling bottleneck at 10x traffic?",
    ],
    questionFamily: "system-feed",
    difficulty: "challenging",
    companyTags: ["general", "meta"],
    interviewerGoal: "Test architectural trade-offs under ranking and scale pressure.",
    followUpPolicy: "Force trade-off choices instead of broad hybrid answers with no decision.",
    coachingOutline: [
      "State the read/write path choice early.",
      "Explain how ranking changes the data flow.",
      "Name the first bottleneck and mitigation.",
    ],
    rubricKeys: ["requirements", "architecture", "scalability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 27,
  }),
  buildQuestion({
    id: "question_system_feed_02",
    mode: "system-design",
    title: "Personalized activity feed",
    prompt: "Design a personalized activity feed that balances relevance, recency, and cost.",
    followUps: [
      "Where would you compute ranking features?",
      "How do you keep hot users from dominating the system?",
      "What product trade-off would you expose to leadership?",
    ],
    questionFamily: "system-feed",
    difficulty: "stretch",
    companyTags: ["general", "google"],
    interviewerGoal: "Expose trade-offs between ranking quality and operational cost.",
    followUpPolicy: "Probe on cost, caching, and fairness under skewed workloads.",
    coachingOutline: [
      "Name the ranking inputs and when they are computed.",
      "Handle hot-key skew explicitly.",
      "Defend one quality-vs-cost trade-off clearly.",
    ],
    rubricKeys: ["requirements", "architecture", "scalability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 28,
  }),
  buildQuestion({
    id: "question_system_rate_limit_01",
    mode: "system-design",
    title: "Global rate limiter",
    prompt: "Design a global rate-limiting service used by multiple APIs across regions.",
    followUps: [
      "What consistency guarantees actually matter here?",
      "How do you handle regional failure or partition?",
      "What API contract makes the limiter usable by product teams?",
    ],
    questionFamily: "system-rate-limit",
    difficulty: "challenging",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Measure consistency reasoning and practical API design.",
    followUpPolicy: "Force the candidate to choose acceptable inconsistency rather than chasing perfect global accuracy.",
    coachingOutline: [
      "State the policy model before the storage choice.",
      "Choose the acceptable consistency trade-off explicitly.",
      "Discuss partition behavior instead of ignoring it.",
    ],
    rubricKeys: ["requirements", "api-data-model", "reliability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 29,
  }),
  buildQuestion({
    id: "question_system_rate_limit_02",
    mode: "system-design",
    title: "Burst control gateway",
    prompt: "Design an API gateway that absorbs sudden traffic bursts while enforcing per-tenant limits.",
    followUps: [
      "Where do queues, buffering, and backpressure belong?",
      "How do you protect smaller tenants from noisy neighbors?",
      "What telemetry do operators need to trust the system?",
    ],
    questionFamily: "system-rate-limit",
    difficulty: "stretch",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Evaluate multi-tenant fairness, backpressure, and operator visibility.",
    followUpPolicy: "Probe on overload behavior and fairness instead of generic throttling language.",
    coachingOutline: [
      "Describe the overload path explicitly.",
      "Name how fairness is enforced per tenant.",
      "Close with the operator signals that prove the design is healthy.",
    ],
    rubricKeys: ["architecture", "scalability", "reliability"],
    sourceTag: "system_design",
    orderIndex: 30,
  }),
  buildQuestion({
    id: "question_system_messaging_01",
    mode: "system-design",
    title: "Team chat",
    prompt: "Design a team chat system with channels, message history, and online presence.",
    followUps: [
      "How do you separate the realtime path from the history path?",
      "What consistency is acceptable for presence?",
      "How do you recover when a websocket region fails?",
    ],
    questionFamily: "system-messaging",
    difficulty: "challenging",
    companyTags: ["general", "meta"],
    interviewerGoal: "Test realtime architecture plus state-model trade-offs.",
    followUpPolicy: "Require separate reasoning for transport, storage, and presence semantics.",
    coachingOutline: [
      "Split realtime delivery from history storage.",
      "Treat presence as approximate, not perfect truth.",
      "Describe region failover before closing.",
    ],
    rubricKeys: ["architecture", "api-data-model", "reliability"],
    sourceTag: "system_design",
    orderIndex: 31,
  }),
  buildQuestion({
    id: "question_system_messaging_02",
    mode: "system-design",
    title: "Support inbox",
    prompt: "Design a support inbox that combines human agents, message history, and SLA-driven routing.",
    followUps: [
      "What is the core data model for conversations and assignments?",
      "How do you rebalance work when one region falls behind?",
      "What failure mode creates the most user-visible damage?",
    ],
    questionFamily: "system-messaging",
    difficulty: "stretch",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Measure queueing, assignment, and operator-facing design choices.",
    followUpPolicy: "Push on backlog behavior, assignment changes, and failure visibility.",
    coachingOutline: [
      "Anchor on conversation and assignment records.",
      "Explain backlog rebalancing explicitly.",
      "Name the user-visible failure mode you optimize against.",
    ],
    rubricKeys: ["requirements", "api-data-model", "reliability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 32,
  }),
  buildQuestion({
    id: "question_system_search_01",
    mode: "system-design",
    title: "Search autocomplete",
    prompt: "Design a search autocomplete system that serves low-latency suggestions as users type.",
    followUps: [
      "What data structure or index supports the latency target?",
      "How do updates flow into the index without hurting read performance?",
      "How do you handle hot prefixes?",
    ],
    questionFamily: "system-search",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Evaluate read-heavy indexing and skew handling.",
    followUpPolicy: "Probe on read/write separation and hot-key mitigation.",
    coachingOutline: [
      "State the latency target before architecture.",
      "Explain the index refresh path.",
      "Call out hot-prefix mitigation and cache invalidation.",
    ],
    rubricKeys: ["requirements", "architecture", "scalability"],
    sourceTag: "system_design",
    orderIndex: 33,
  }),
  buildQuestion({
    id: "question_system_search_02",
    mode: "system-design",
    title: "Internal developer search",
    prompt: "Design an internal code and documentation search service with freshness requirements.",
    followUps: [
      "What ingestion path keeps the index fresh enough?",
      "How do you expose ranking or relevance knobs safely?",
      "What trade-off would you make between freshness and cost?",
    ],
    questionFamily: "system-search",
    difficulty: "stretch",
    companyTags: ["general", "google", "stripe"],
    interviewerGoal: "Test freshness vs cost trade-offs in search-oriented systems.",
    followUpPolicy: "Force one concrete freshness trade-off instead of a generic 'eventually consistent' answer.",
    coachingOutline: [
      "Define the freshness target numerically.",
      "Explain ingestion and re-indexing separately.",
      "Defend the cost-quality trade-off at the end.",
    ],
    rubricKeys: ["requirements", "architecture", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 34,
  }),
  buildQuestion({
    id: "question_system_analytics_01",
    mode: "system-design",
    title: "Product analytics pipeline",
    prompt: "Design a product analytics pipeline that supports real-time dashboards and historical backfills.",
    followUps: [
      "How do you separate the realtime and backfill paths?",
      "Where does schema evolution become risky?",
      "What guarantees do downstream dashboards actually need?",
    ],
    questionFamily: "system-analytics",
    difficulty: "challenging",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Assess event ingestion, storage, and correctness trade-offs.",
    followUpPolicy: "Probe on late data, schema versioning, and consumer expectations.",
    coachingOutline: [
      "Split low-latency and backfill concerns early.",
      "Explain event schema ownership and evolution.",
      "Name the guarantee you are actually optimizing for.",
    ],
    rubricKeys: ["requirements", "architecture", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 35,
  }),
  buildQuestion({
    id: "question_system_analytics_02",
    mode: "system-design",
    title: "Fraud event pipeline",
    prompt: "Design an event processing pipeline that scores suspicious transactions with both streaming and batch features.",
    followUps: [
      "What data needs streaming freshness and what can lag?",
      "How do you protect scoring from duplicate or delayed events?",
      "What fallback exists when the scoring service is degraded?",
    ],
    questionFamily: "system-analytics",
    difficulty: "stretch",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Test architecture under correctness and latency pressure.",
    followUpPolicy: "Push on idempotency, degraded mode, and feature freshness.",
    coachingOutline: [
      "State which features must be realtime.",
      "Defend idempotency and replay handling.",
      "Describe degraded scoring behavior explicitly.",
    ],
    rubricKeys: ["requirements", "reliability", "trade-offs"],
    sourceTag: "system_design",
    orderIndex: 36,
  }),
  buildQuestion({
    id: "question_resume_scope_01",
    mode: "resume",
    title: "Highest-risk project",
    prompt: "Walk me through the project on your resume that carried the highest operational risk.",
    followUps: [
      "What part did you personally own?",
      "Why was the solution credible rather than just ambitious?",
      "What result on the resume needs the most proof in an interview?",
    ],
    questionFamily: "resume-risk",
    difficulty: "standard",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Pressure the most impressive resume claim first.",
    followUpPolicy: "Challenge the claim until the candidate names the real scope and proof.",
    coachingOutline: [
      "Choose one claim and own the scope clearly.",
      "Defend the technical choice with detail.",
      "Close with the strongest proof point.",
    ],
    rubricKeys: ["credibility", "scope", "technical-depth", "impact"],
    sourceTag: "resume_review",
    orderIndex: 37,
  }),
  buildQuestion({
    id: "question_resume_scope_02",
    mode: "resume",
    title: "Most credible bullet",
    prompt: "Pick the strongest bullet on your resume and defend it as if I am skeptical.",
    followUps: [
      "What exactly changed because of that work?",
      "What would a teammate say you specifically contributed?",
      "What technical detail proves the bullet is not inflated?",
    ],
    questionFamily: "resume-risk",
    difficulty: "challenging",
    companyTags: ["general", "google"],
    interviewerGoal: "Test whether the candidate can defend resume bullets under direct pressure.",
    followUpPolicy: "Keep asking for specific proof until the claim sounds grounded.",
    coachingOutline: [
      "Choose the most defensible bullet, not the flashiest one.",
      "Show direct contribution and technical mechanism.",
      "End with measurable impact.",
    ],
    rubricKeys: ["credibility", "scope", "impact"],
    sourceTag: "resume_review",
    orderIndex: 38,
  }),
  buildQuestion({
    id: "question_resume_leadership_01",
    mode: "resume",
    title: "Leadership claim",
    prompt: "Your resume implies leadership. Tell me about the most substantive leadership decision behind that claim.",
    followUps: [
      "What made it leadership rather than just execution?",
      "How did you influence adoption?",
      "What risk did you personally absorb in making that call?",
    ],
    questionFamily: "resume-leadership",
    difficulty: "challenging",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Differentiate real leadership from inflated wording.",
    followUpPolicy: "Probe for system or people leverage, not just task ownership.",
    coachingOutline: [
      "Explain the decision before the coordination details.",
      "Name the influence mechanism.",
      "Show the risk you personally owned.",
    ],
    rubricKeys: ["credibility", "decision-quality", "impact"],
    sourceTag: "resume_review",
    orderIndex: 39,
  }),
  buildQuestion({
    id: "question_resume_leadership_02",
    mode: "resume",
    title: "Architectural ownership claim",
    prompt: "There is an architecture-heavy bullet on your resume. Walk me through the actual decision that bullet compresses.",
    followUps: [
      "What alternatives did you reject?",
      "What technical trade-off would you still defend today?",
      "What detail would expose exaggeration if you did not really own it?",
    ],
    questionFamily: "resume-leadership",
    difficulty: "stretch",
    companyTags: ["general", "meta"],
    interviewerGoal: "Stress-test architecture claims for authenticity and depth.",
    followUpPolicy: "Push on alternatives, trade-offs, and mechanism-level detail.",
    coachingOutline: [
      "Expand the bullet into a real decision story.",
      "Defend the alternative you rejected.",
      "Name the implementation detail only the owner would know.",
    ],
    rubricKeys: ["credibility", "decision-quality", "technical-depth"],
    sourceTag: "resume_review",
    orderIndex: 40,
  }),
  buildQuestion({
    id: "question_resume_metrics_01",
    mode: "resume",
    title: "Metrics proof",
    prompt: "Choose a resume bullet with a metric in it. How do you know that metric was caused by your work?",
    followUps: [
      "What other factors could have confounded the result?",
      "What measurement was weakest in that claim?",
      "How would you phrase the bullet more carefully today?",
    ],
    questionFamily: "resume-metrics",
    difficulty: "challenging",
    companyTags: ["general", "google", "stripe"],
    interviewerGoal: "Measure causal reasoning and intellectual honesty in resume claims.",
    followUpPolicy: "Push on attribution quality and careful phrasing.",
    coachingOutline: [
      "State the metric and the causal claim separately.",
      "Acknowledge confounders without surrendering ownership.",
      "Show how you would rewrite the bullet more honestly and strongly.",
    ],
    rubricKeys: ["credibility", "impact", "communication"],
    sourceTag: "resume_review",
    orderIndex: 41,
  }),
  buildQuestion({
    id: "question_resume_metrics_02",
    mode: "resume",
    title: "Impact under challenge",
    prompt: "Tell me about the most important impact statement on your resume and why I should believe it.",
    followUps: [
      "What exact system or user behavior changed?",
      "Where is the uncertainty in that result?",
      "What follow-up would most likely catch someone bluffing?",
    ],
    questionFamily: "resume-metrics",
    difficulty: "standard",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Test whether the candidate can defend impact without overstating certainty.",
    followUpPolicy: "Probe on mechanism, uncertainty, and proof quality.",
    coachingOutline: [
      "Tie the metric to the system change.",
      "Acknowledge uncertainty with precision.",
      "Answer the bluff-detection follow-up directly.",
    ],
    rubricKeys: ["credibility", "impact", "technical-depth"],
    sourceTag: "resume_review",
    orderIndex: 42,
  }),
  buildQuestion({
    id: "question_project_architecture_01",
    mode: "project",
    title: "Architecture deep dive",
    prompt: "Choose one project and explain the architecture as if I had not seen the codebase.",
    followUps: [
      "Which boundary or dependency was the riskiest choice?",
      "What did you deliberately leave out of the architecture?",
      "What would you redesign first if usage doubled?",
    ],
    questionFamily: "project-architecture",
    difficulty: "standard",
    companyTags: ["general", "meta"],
    interviewerGoal: "Measure architecture communication and trade-off quality.",
    followUpPolicy: "Keep the candidate anchored to boundaries and trade-offs rather than a timeline recap.",
    coachingOutline: [
      "Start with the top-level components and data flow.",
      "Name the riskiest boundary clearly.",
      "Defend what you omitted as well as what you built.",
    ],
    rubricKeys: ["scope", "decision-quality", "technical-depth", "impact"],
    sourceTag: "project_walkthrough",
    orderIndex: 43,
  }),
  buildQuestion({
    id: "question_project_architecture_02",
    mode: "project",
    title: "Architecture trade-off",
    prompt: "Describe a project decision where you chose a worse short-term solution for a better long-term result.",
    followUps: [
      "What immediate pain did that create?",
      "How did you justify the long-term bet?",
      "What evidence later proved the decision was worth it?",
    ],
    questionFamily: "project-architecture",
    difficulty: "challenging",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Test whether the candidate can defend long-term trade-offs with evidence.",
    followUpPolicy: "Probe on immediate cost and delayed payoff instead of accepting principle-level answers.",
    coachingOutline: [
      "Name the short-term pain explicitly.",
      "Explain the long-term value in system terms.",
      "Prove the bet paid off with a concrete signal.",
    ],
    rubricKeys: ["decision-quality", "technical-depth", "impact"],
    sourceTag: "project_walkthrough",
    orderIndex: 44,
  }),
  buildQuestion({
    id: "question_project_delivery_01",
    mode: "project",
    title: "Delivery under pressure",
    prompt: "Tell me about the hardest delivery trade-off you made on a project you still feel proud of.",
    followUps: [
      "What scope or quality bar moved because of the deadline?",
      "How did you keep the project maintainable anyway?",
      "What would you challenge if another engineer presented the same story?",
    ],
    questionFamily: "project-delivery",
    difficulty: "challenging",
    companyTags: ["general", "amazon"],
    interviewerGoal: "Pressure delivery judgment without losing technical credibility.",
    followUpPolicy: "Probe on what was cut, what was preserved, and why.",
    coachingOutline: [
      "Describe the delivery constraint first.",
      "Name the quality bar you protected.",
      "Defend the cut or compromise in explicit trade-off language.",
    ],
    rubricKeys: ["scope", "decision-quality", "impact", "communication"],
    sourceTag: "project_walkthrough",
    orderIndex: 45,
  }),
  buildQuestion({
    id: "question_project_delivery_02",
    mode: "project",
    title: "Maintainability choice",
    prompt: "Describe a project where you protected maintainability even though it slowed the first release.",
    followUps: [
      "What exactly did you do for maintainability?",
      "How did you know it was worth the delay?",
      "What follow-up metric or signal would prove you were right?",
    ],
    questionFamily: "project-delivery",
    difficulty: "standard",
    companyTags: ["general", "google"],
    interviewerGoal: "Test whether the candidate can make maintainability tangible.",
    followUpPolicy: "Push the answer toward concrete design choices and proof, not generic code quality language.",
    coachingOutline: [
      "Name the maintainability investment specifically.",
      "Explain the release trade-off clearly.",
      "Close with the proof it paid off.",
    ],
    rubricKeys: ["decision-quality", "technical-depth", "impact"],
    sourceTag: "project_walkthrough",
    orderIndex: 46,
  }),
  buildQuestion({
    id: "question_project_scaling_01",
    mode: "project",
    title: "Scale challenge",
    prompt: "Walk me through a project that became harder as adoption grew.",
    followUps: [
      "What bottleneck showed up first?",
      "What architectural change did you make?",
      "How did you verify the fix helped at the new scale?",
    ],
    questionFamily: "project-scaling",
    difficulty: "challenging",
    companyTags: ["general", "meta"],
    interviewerGoal: "Evaluate whether the project story matures into systems thinking.",
    followUpPolicy: "Probe on the specific bottleneck and the validation signal after the fix.",
    coachingOutline: [
      "Name the first scaling pain clearly.",
      "Explain the architectural response in one pass.",
      "Close with the measurement that proved the change worked.",
    ],
    rubricKeys: ["technical-depth", "impact", "decision-quality"],
    sourceTag: "project_walkthrough",
    orderIndex: 47,
  }),
  buildQuestion({
    id: "question_project_scaling_02",
    mode: "project",
    title: "System maturity upgrade",
    prompt: "Tell me about a project where you had to evolve a proof-of-concept into something production-ready.",
    followUps: [
      "What broke first as you hardened it?",
      "What did you remove or redesign from the prototype?",
      "What sign told you the project was finally production-grade?",
    ],
    questionFamily: "project-scaling",
    difficulty: "standard",
    companyTags: ["general", "stripe"],
    interviewerGoal: "Test the candidate's ability to explain maturity upgrades, not just initial construction.",
    followUpPolicy: "Probe on what changed between prototype and production and why.",
    coachingOutline: [
      "Contrast the prototype with the production version.",
      "Name the first production-grade gap that mattered.",
      "Explain the signal that made you trust the system.",
    ],
    rubricKeys: ["scope", "technical-depth", "impact"],
    sourceTag: "project_walkthrough",
    orderIndex: 48,
  }),
 ] as const satisfies readonly QuestionSeed[];

export const SEED_PROMPT_VERSIONS = [
  {
    id: "prompt_voice_interviewer_guided_v2",
    label: "Voice interviewer guided v2",
    model: "gpt-realtime",
    hash: "sha256:voice-interviewer-guided-v2",
    notes: "Guided interviewer prompt for staged drills with progressive hints.",
  },
  {
    id: "prompt_voice_interviewer_live_v2",
    label: "Voice interviewer live v2",
    model: "gpt-realtime",
    hash: "sha256:voice-interviewer-live-v2",
    notes: "Live interviewer prompt for pressure simulation without leaking solutions.",
  },
  {
    id: "prompt_scorecard_v2",
    label: "Scorecard v2",
    model: "gpt-5.2",
    hash: "sha256:scorecard-v2",
    notes: "Track-specific rubric prompt for evidence-grounded feedback artifacts.",
  },
] as const satisfies readonly NewPromptVersionRow[];

export const SEED_EVAL_CASES = [
  {
    id: "eval_behavioral_band_v2",
    name: "Behavioral ownership baseline",
    mode: "behavioral",
    expectedBand: "improving",
    fixturePath: "tests/fixtures/evals/behavioral-ownership.json",
  },
  {
    id: "eval_coding_band_v2",
    name: "Coding reasoning baseline",
    mode: "coding",
    expectedBand: "improving",
    fixturePath: "tests/fixtures/evals/coding-reasoning.json",
  },
  {
    id: "eval_system_design_band_v2",
    name: "System design tradeoff baseline",
    mode: "system-design",
    expectedBand: "training",
    fixturePath: "tests/fixtures/evals/system-design-notification.json",
  },
] as const satisfies readonly NewEvalCaseRow[];

export const INTERVIEW_SEED = {
  rubricDimensions: SEED_RUBRIC_DIMENSIONS,
  questionBank: SEED_QUESTION_BANK,
  promptVersions: SEED_PROMPT_VERSIONS,
  evalCases: SEED_EVAL_CASES,
} as const;

export function getSeedQuestionBank(mode?: InterviewMode) {
  return mode
    ? SEED_QUESTION_BANK.filter((question) => question.mode === mode)
    : SEED_QUESTION_BANK;
}
